# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Beam中国'
description: "致力于打造国内最优秀的Beam社区。"

# Author's info
author: '相国'
# edit 'categories' in the front matter of every post to match this username
nickname: 相国
bio: '一个热爱coding的骚年'
location: '杭州'
url: 'http://beam-china.com'
image: 'assets/images/casper.png'

short_url: 'beam-china.com'
google_analytics: UA-53248719-2
disqus: xiangguo
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: litongbupt
repo: beam-china
branch: master
relative_source: ../beam-china/
destination: ../beam-china-pages/
production_url:  https://litongbupt.github.io/beam-china
source_url:      https://github.com/litongbupt/beam-china

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
